$(function(){
    $(".nav-link").mouseleave(function(){
        $(this).css("color","black");
    }).mouseenter(function(){
        $(this).css("color","darkgreen");
    });
    $(".dropdown-item").mousedown(function(){
        $(this).css("background-color","darkgreen");
    }).mouseup(function(){
        $(this).css("background-color","white");
    });
});